In [2]:
import numpy as np

In [ ]:
a=np.arange(10,51)
print(a[::2])

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
b=np.linspace(0,1,9)
print(b)

[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]


In [ ]:
a1=np.full((5,5),1)
a1[1:4,1:4]=0
print(a1)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [7]:
s=np.array(["Stores_A","Stores_B","Stores_C","Stores_D","Stores_E"])
sales=np.array([[120000,135000,142000,155000],[98000,105000,110000,108000],[150000,148000,160000,172000],[87000,92000,99000,115000],[130000,138000,141000,149000]])
c=np.sum(sales,axis=1)
print(c)

[552000 421000 630000 393000 558000]


In [ ]:
q=np.mean(sales,axis=1)
print(q)

[138000. 105250. 157500.  98250. 139500.]


In [ ]:
w=np.sum(sales,axis=0)
print(w)

[585000 618000 652000 699000]


In [ ]:
r=np.argmax(sales,axis=1)
print(s[r])

['Stores_D' 'Stores_C' 'Stores_D' 'Stores_D' 'Stores_D']


In [12]:
c=np.sum(sales,axis=1)
print(c)

[552000 421000 630000 393000 558000]


In [11]:
ranking = np.argsort(c)[::-1]
print(s[ranking])

['Stores_C' 'Stores_E' 'Stores_A' 'Stores_B' 'Stores_D']


In [15]:
overall_avg = np.mean(c)
above_avg = s[c > overall_avg]
print(above_avg)

['Stores_A' 'Stores_C' 'Stores_E']


In [16]:
students = np.array(["Anu", "Binu", "Cathy",
                     "Deepa", "Ebin", "Fahad"])

marks = np.array([
    [82, 75, 91, 88],
    [61, 68, 70, 65],
    [45, 52, 48, 55],
    [90, 94, 89, 92],
    [72, 80, 76, 85],
    [38, 42, 49, 44]
])

subjects = np.array(["Python", "SQL",
                     "Excel", "Statistics"])

In [17]:
# Total and average marks for each student
total = np.sum(marks, axis=1)
average = np.mean(marks, axis=1)
print("Total Marks:", total)
print("Average Marks:", average)

Total Marks: [336 264 200 365 313 173]
Average Marks: [84.   66.   50.   91.25 78.25 43.25]


In [18]:
# Subject averages
subject_avg = np.mean(marks, axis=0)
print("Subject Averages:", subject_avg)

Subject Averages: [64.66666667 68.5        70.5        71.5       ]


In [19]:
# Highest mark in each subject
highest_marks = np.max(marks, axis=0)
print("Highest Marks:", highest_marks)

Highest Marks: [90 94 91 92]


In [20]:
# Pass/fail status for every subject
status = np.where(marks >= 50, "Pass", "Fail")
print(status)

[['Pass' 'Pass' 'Pass' 'Pass']
 ['Pass' 'Pass' 'Pass' 'Pass']
 ['Fail' 'Pass' 'Fail' 'Pass']
 ['Pass' 'Pass' 'Pass' 'Pass']
 ['Pass' 'Pass' 'Pass' 'Pass']
 ['Fail' 'Fail' 'Fail' 'Fail']]


In [21]:
# Students who passed every subject
fullpass = np.all(marks >= 50, axis=1)
print("Passed All Subjects:", students[fullpass])

Passed All Subjects: ['Anu' 'Binu' 'Deepa' 'Ebin']


In [22]:
# Students whose average is below 60
below_60 = students[average < 60]
print("Average Below 60:", below_60)

Average Below 60: ['Cathy' 'Fahad']


In [23]:
employees = np.array([
    "Arun", "Bhavana", "Charan",
    "Divya", "Eshan", "Fathima"
])

performance = np.array([
    [78, 82, 85, 88],
    [65, 70, 68, 74],
    [92, 89, 95, 91],
    [55, 62, 60, 67],
    [81, 79, 84, 87],
    [72, 75, 78, 80]
])

quarters = np.array(["Q1", "Q2", "Q3", "Q4"])

In [24]:
# Total performance score of every employee
total = np.sum(performance, axis=1)
print("Total Scores:", total)

Total Scores: [333 277 367 244 331 305]


In [25]:
# Average quarterly performance per employee
avg = np.mean(performance, axis=1)
print("Employee Averages:", avg)

Employee Averages: [83.25 69.25 91.75 61.   82.75 76.25]


In [28]:
# Average performance for each quarter
quarter_avg = np.mean(performance, axis=0)
print("Quarterly Averages:", quarter_avg)

Quarterly Averages: [73.83333333 76.16666667 78.33333333 81.16666667]


In [29]:
# Employee with highest total score
highest = np.argmax(total)
print("Highest Performer:", employees[highest])

Highest Performer: Charan


In [30]:
# Rank employees by total score
ranking = np.argsort(total)[::-1]
print("Ranking:", employees[ranking])

Ranking: ['Charan' 'Arun' 'Eshan' 'Fathima' 'Bhavana' 'Divya']


In [38]:
# Quarter-over-quarter percentage growth
growth = (np.diff(performance, axis=1) / performance[:, :-1]) * 100
print("Percentage Growth:")
print(np.round(growth, 2))

Percentage Growth:
[[ 5.13  3.66  3.53]
 [ 7.69 -2.86  8.82]
 [-3.26  6.74 -4.21]
 [12.73 -3.23 11.67]
 [-2.47  6.33  3.57]
 [ 4.17  4.    2.56]]


In [35]:
# Employees with average >= 80
print("Average >= 80:", employees[avg >= 80])

Average >= 80: ['Arun' 'Charan' 'Eshan']


In [34]:
# Count employees with average below 70
count = np.sum(avg < 70)
print("Count Below 70:", count)

Count Below 70: 2


In [36]:
# Highest score in entire dataset
maximum = np.max(performance)
print("Highest Score:", maximum)

Highest Score: 95


In [37]:
# Employee and quarter of highest score
row, col = np.where(performance == np.max(performance))

print("Employee:", employees[row])
print("Quarter:", quarters[col])

Employee: ['Charan']
Quarter: ['Q3']
